"""Generate the deterministic genuine GIF fixtures used by the GIF regression tests.

Provenance: authored for NaguMIX GIF regression coverage on 2026-09-12 and encoded with
Pillow's GIF89a writer. The test expectations are specified independently as
logical-canvas RGBA landmarks; they are not generated by the decode helper.
"""

from pathlib import Path

from PIL import Image


FIXTURE_DIR = Path(__file__).resolve().parent
SIZE = (6, 4)


def palette(*colors):
    values = []
    for color in colors:
        values.extend(color)
    return values + [0] * (768 - len(values))


def indexed_frame(colors, painted):
    image = Image.new("P", SIZE, 0)
    image.putpalette(palette(*colors))
    for box, index in painted:
        image.paste(index, box)
    image.info["transparency"] = 0
    return image


def make_disposal_fixture():
    # Every frame deliberately uses a different local palette. Transparent
    # index zero lets disposal=2 expose alpha in the prior update rectangle.
    frames = [
        indexed_frame(
            ((0, 0, 0), (220, 20, 20)),
            [((0, 0, 6, 4), 1), ((5, 0, 6, 1), 0)]),
        indexed_frame(((0, 0, 0), (20, 210, 30)), [((1, 1, 3, 3), 1)]),
        indexed_frame(((0, 0, 0), (30, 60, 220)), [((3, 1, 5, 3), 1)]),
        indexed_frame(((0, 0, 0), (240, 210, 20)), [((5, 3, 6, 4), 1)]),
    ]
    frames[0].save(
        FIXTURE_DIR / "regression_27_disposal.gif",
        save_all=True,
        append_images=frames[1:],
        duration=[80, 90, 100, 110],
        disposal=[1, 2, 3, 1],
        transparency=0,
        loop=0,
        optimize=True,
        include_color_table=True,
    )
    for frame in frames:
        frame.close()


def make_random_seek_fixture():
    frames = [
        indexed_frame(
            ((0, 0, 0), (30, 30, 30)),
            [((0, 0, 6, 4), 1), ((5, 0, 6, 1), 0)]),
        indexed_frame(((0, 0, 0), (180, 40, 180)), [((0, 0, 2, 2), 1)]),
        indexed_frame(((0, 0, 0), (20, 180, 180)), [((2, 1, 4, 3), 1)]),
        indexed_frame(((0, 0, 0), (240, 120, 20)), [((4, 2, 6, 4), 1)]),
    ]
    frames[0].save(
        FIXTURE_DIR / "regression_27_random_seek.gif",
        save_all=True,
        append_images=frames[1:],
        duration=[40, 50, 60, 70],
        disposal=[1, 1, 1, 1],
        transparency=0,
        loop=0,
        optimize=True,
        include_color_table=True,
    )
    for frame in frames:
        frame.close()


def make_single_frame_fixture():
    image = indexed_frame(
        ((0, 0, 0), (12, 100, 220)), [((0, 0, 6, 4), 1)])
    image.save(
        FIXTURE_DIR / "regression_27_single.gif",
        transparency=0,
        duration=125,
        optimize=False,
    )
    image.close()


if __name__ == "__main__":
    make_disposal_fixture()
    make_random_seek_fixture()
    make_single_frame_fixture()
